# filepath: [Dockerfile.frontend](http://_vscodecontentref_/1)

# Usar imagem base do Node.js
FROM node:16

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos do projeto
COPY [package.json](http://_vscodecontentref_/2) [package-lock.json](http://_vscodecontentref_/3) ./

# Instalar dependências
RUN npm install

# Copiar o restante do código
COPY ./frontend .

# Expor a porta do React
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "start"]